LANGUAGES = {
    "en": {
        "no_ratings": "No ratings found.",
        "invalid_page": "Invalid page number. Please choose between 1 and {total_pages}.",
        "top_users_title": "🏆 Top Rated Users",
        "page_display": "Page {current}/{total}",
        "rating_display": "Rating: {rating}",
        "rating_info_title": "📊 Rating Information",
        "user_field": "User",
        "rating_field": "Rating",
        "user_no_rating": "{user} has no rating.",
        "rating_added": "✨ Added {amount} points to {user}'s rating. New rating: {rating}",
        "rating_removed": "📉 Removed {amount} points from {user}'s rating. New rating: {rating}",
        "no_admin_role": "Admin role not set up! Ask an administrator to use /setupadmin first.",
        "no_permission": "You don't have permission to use this command!",
        "no_rating_setup": "Rating system not set up! Use /setuprating first.",
        "no_required_role": "{user} doesn't have the required role!",
        "rating_setup": "Rating system set up for role: {role}",
        "admin_setup": "Rating management role set to: {role}",
        "prev_button": "Previous",
        "next_button": "Next",
        "setup_title": "⚙️ Rating System Setup",
        "setup_description": "System configuration has been updated",
        "rated_role_title": "📊 Rated Role",
        "rated_role_desc": "Members with this role can receive ratings",
        "admin_role_title": "👑 Admin Role",
        "admin_role_desc": "Members with this role can manage ratings",
        "setup_status": "✅ Setup completed successfully\n📝 Initial ratings have been initialized",
        "language_updated": "Language has been set to English",
        "language_title": "🌐 Language Settings",
        "language_description": "Server language has been updated",
    },
    "ru": {
        "no_ratings": "Рейтинги не найдены.",
        "invalid_page": "Неверный номер страницы. Выберите от 1 до {total_pages}.",
        "top_users_title": "🏆 Топ пользователей",
        "page_display": "Страница {current}/{total}",
        "rating_display": "Рейтинг: {rating}",
        "rating_info_title": "📊 Информация о рейтинге",
        "user_field": "Пользователь",
        "rating_field": "Рейтинг",
        "user_no_rating": "У {user} нет рейтинга.",
        "rating_added": "✨ Добавлено {amount} очков рейтинга для {user}. Новый рейтинг: {rating}",
        "rating_removed": "📉 Удалено {amount} очков рейтинга у {user}. Новый рейтинг: {rating}",
        "no_admin_role": "Роль администратора не настроена! Попросите администратора использовать /setupadmin.",
        "no_permission": "У вас нет прав на использование этой команды!",
        "no_rating_setup": "Система рейтинга не настроена! Используйте /setuprating.",
        "no_required_role": "У {user} нет необходимой роли!",
        "rating_setup": "Система рейтинга настроена для роли: {role}",
        "admin_setup": "Роль управления рейтингом установлена: {role}",
        "prev_button": "Назад",
        "next_button": "Вперед",
        "setup_title": "⚙️ Настройка системы рейтинга",
        "setup_description": "Конфигурация системы обновлена",
        "rated_role_title": "📊 Оцениваемая роль",
        "rated_role_desc": "Участники с этой ролью могут получать рейтинг",
        "admin_role_title": "👑 Роль администратора",
        "admin_role_desc": "Участники с этой ролью могут управлять рейтингом",
        "setup_status": "✅ Настройка успешно завершена\n📝 Начальные рейтинги инициализированы",
        "language_updated": "Язык установлен на русский",
        "language_title": "🌐 Настройки языка",
        "language_description": "Язык сервера был обновлен",
    }
}